project:
  type: website
  output-dir: docs

website:
  title: "Lithobius"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - pages/about.qmd
      - pages/testpage.qmd

format:
  html:
    respect-user-color-scheme: true
    theme:
      - yeti
      - brand
    css: styles.css
    toc: true

editor: visual

